# Generated by Django 4.2.7 on 2024-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('algorithm', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('time_elapsed', models.FloatField()),
                ('primes', models.TextField()),
            ],
        ),
    ]
